---

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    force: yes
    owner: root
    group: docker
    mode: 0750

- name: create /etc/docker/compose directory
  file:
    path: /etc/docker/compose
    state: directory
    owner: root
    group: docker
    mode: 0770

- name: create /etc/docker/compose directory
  file:
    src: /etc/docker/compose
    dest: /home/{{ docker_user }}/compose-services
    state: link
  when: docker_user is defined

- name: create docker-compose multi-service file
  template:
    src: docker-compose.service.j2
    dest: /etc/systemd/system/docker-compose@.service
    owner: root
    group: root
    mode: 0644
  notify:
    - run daemon-reload
