---
- name: add docker repository
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
    mode: 0644
  register: repo_added

- name: remove legacy docker package
  yum:
    pkg: docker
    state: absent
  when: repo_added.changed

- name: install docker
  yum:
    pkg: "docker-ce-{{ docker_version }}"
    state: installed
  notify: restart docker

- name: update docker systemd service file
  template:
    src: docker.service.j2
    dest: /usr/lib/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
  notify:
    - run daemon-reload
    - restart docker

- name: enable docker
  service:
    name: docker
    enabled: yes

- name: create a non-root system user for docker management
  import_tasks: docker-user.yml
  tags: docker-user

- name: be ready to run services based on docker-compose
  import_tasks: docker-compose.yml
  tags: docker-compose
  when: docker_compose_version is defined

- name: configure a docker housekeeping cronjob
  become: yes
  become_user: "{{ docker_user|default('root') }}"
  cron:
    name: Docker clean up
    job: docker system prune -af
    minute: '1'
    hour: '1'
    day: '*'
    month: '*'
    weekday: '0'
    disabled: "{{ not (docker_cleanup_cronjob|bool) }}"

- meta: flush_handlers
