---
- name: add docker repository
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
    mode: 0644
  register: repo_added

- name: remove legacy docker package
  yum:
    pkg: docker
    state: absent
  when: repo_added.changed

- name: install yum-plugin-versionlock
  yum:
   pkg: yum-plugin-versionlock
  when: docker_pinversion

- name: unpin version
  shell: yum versionlock delete docker-ce
  args:
    warn: no
  when: not docker_pinversion
  register: cmd_unpinversion
  changed_when: "'versionlock deleted: 1' in cmd_unpinversion.stdout"
  failed_when: false

- name: install docker
  yum:
    pkg: "docker-ce-{{ docker_version }}"
    state: installed
    disable_plugin: versionlock
    allow_downgrade: true
  register: cmd_installdocker
  notify: restart docker

- name: unpin version
  shell: yum versionlock delete docker-ce
  args:
    warn: no
  when: docker_pinversion and cmd_installdocker.changed
  register: cmd_unpinversion2
  changed_when: "'versionlock deleted: 1' in cmd_unpinversion2.stdout"
  failed_when: false

- name: pin version
  shell: yum versionlock add docker-ce
  args:
    warn: no
  when: docker_pinversion
  register: cmd_pinversion
  changed_when: "'versionlock added: 1' in cmd_pinversion.stdout"

- name: update docker systemd service file
  template:
    src: docker.service.j2
    dest: /usr/lib/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
  notify:
    - run daemon-reload
    - restart docker

- name: enable docker
  service:
    name: docker
    enabled: yes

- name: create a non-root system user for docker management
  import_tasks: docker-user.yml
  tags: docker-user

- name: be ready to run services based on docker-compose
  import_tasks: docker-compose.yml
  tags: docker-compose
  when: docker_compose_version is defined

- name: configure a docker housekeeping cronjob
  become: yes
  become_user: "{{ docker_user|default('root') }}"
  cron:
    name: Docker clean up
    job: docker system prune -af
    minute: '1'
    hour: '1'
    day: '*'
    month: '*'
    weekday: '0'
    disabled: "{{ not (docker_cleanup_cronjob|bool) }}"

- meta: flush_handlers
