---
- name: run daemon-reload
  systemd:
    daemon_reload: yes

- name: restart docker
  service:
    name: docker
    state: restarted

- name: docker users updated
  debug:
    msg: docker users updates
  listen: docker_users_updated
